# -*- coding: utf-8 -*-

from smile.classification import LDA

import mipylib.numeric as np
from .classifer import Classifer

class LinearDiscriminantAnalysis(Classifer):
    '''
    Linear Discriminant Analysis

    A classifier with a linear decision boundary, generated by fitting class conditional densities 
    to the data and using Bayes’ rule.

    The model fits a Gaussian density to each class, assuming that all classes share the same 
    covariance matrix.

    The fitted model can also be used to reduce the dimensionality of the input by projecting it to 
    the most discriminative directions.

    :param priori: (*array*) The priori probability of each class.
    :param tol: (*float*) a tolerance to decide if a covariance matrix is singular; it will reject 
        variables whose variance is less than tol^2.
    
    :returns: 
    '''
    
    def __init__(self, priori=None, tol=0.0001):
        super(LinearDiscriminantAnalysis, self).__init__()
        
        self.priori = priori
        self.tol = tol
    
    def fit(self, x, y):
        """
        Learn from input data and labels.
        
        :param x: (*array*) Training samples. 2D array.
        :param y: (*array*) Training labels in [0, c), where c is the number of classes.
        """
        super(LinearDiscriminantAnalysis, self).fit(x, y)
        priori = None if self.priori is None else self.priori.tojarray('double')
        self._model = LDA.fit(x.tojarray('double'), y.tojarray('int'), priori, self.tol)
        
        
##################################################